AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  root
  
Resources:

  Api:
    Type: AWS::Serverless::Application
    Properties:
      Location: api.yaml
      Parameters:
        HelloWorldFunctionArn: !GetAtt Lambdas.Outputs.HelloWorldFunctionArn 
  
  Lambdas:
    Type: AWS::Serverless::Application
    Properties:
      Location: lambdas.yaml